pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "CoolDemo"
include ':app'
include ':coollibrary:aoa'
include ':coollibrary:cf'
include ':coollibrary:ff'
include ':coollibrary:media'
